### PR TITLE
validate nested profiles are configured correctly

### LINKED ISSUE #334: PCTL add seems to ignore that path variable specified in a nested profile.
**What were you trying to accomplish?**

I am trying to install a nested from profile inside a profile.

**What happened?**

It seems that is generating the profile from the source location, but when it imports the child profile is using the "." path location instead of the one specified in the profile location.

► generating profile installation from source: repository git@github.com:weaveworksREDACTIED.git, path: ./REDACTIED and branch demo-profile
✗ failed to make artifacts: failed to read profile.yaml in repo "git@github.com:weaveworks/REDACTIED.git" branch "main" path ".": open /var/folders/l5/z__sm53j3bs2p5znngsf96kc0000gn/T/cloned_profiledec0c6924581307/profile.yaml: no such file or directory
make: *** [test] Error 1

    - name: $NAME
      profile:
        source:
          url: git@github.com:weaveworks/{REDACTIED}.git
          tag: main
          path: ./REDACTIED

**How to reproduce it?**

Please reach out individual to me over slack for actual configuration file.

**Logs**

► generating profile installation from source: repository git@github.com:weaveworks/REDACTIED.git, path: ./REDACTIED and branch demo-profile
✗ failed to make artifacts: failed to read profile.yaml in repo "git@github.com:weaveworks/REDACTIED.git" branch "main" path ".": open /var/folders/l5/z_

**Anything else we need to know?**

Mac OS

**Versions**

pctl version 0.11.0

### PR DESCRIPTION
**Pull request by aclevername**
### Description

Closes #334 

### Checklist
- [ ] Added tests that cover your change
- [ ] Added/modified documentation as required (such as the `README.md`)
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

File: pkg/install/installer.go [hunk 1]
```diff
@@ -110,6 +114,17 @@ func (i *Installer) collectArtifacts(installation profilesv1.ProfileInstallation
...
 }
 
+func validateProfileArtifact(p *profilesv1.Profile) error {
+	if p.Source.Tag != "" && p.Source.Branch != "" {
+		return fmt.Errorf("cannot configure both %q and %q in profile artifact", "profile.Source.Tag", "Profile.Source.Branch")
+	}
+
+	if p.Source.Tag == "" && p.Source.Branch == "" {
+		return fmt.Errorf("one of %q or %q must be configured", "profile.Source.Tag", "Profile.Source.Branch")
+	}
```
Comment (aclevername) [inline pkg/install/installer.go:124]: these error formats are a bit odd, but wanted to be clear to the person writing the yaml what fields aren't set correctly.

**Review by Skarlso — APPROVED** [review]

File: pkg/install/installer.go [hunk 2]
```diff
@@ -78,6 +78,10 @@ func (i *Installer) collectArtifacts(installation profilesv1.ProfileInstallation
 	for _, a := range profileDef.Spec.Artifacts {
 		//If its a nested profile lets make a recursive call to scans its artifacts
 		if a.Profile != nil {
+			err := validateProfileArtifact(a.Profile)
```
Comment (Skarlso) [inline pkg/install/installer.go:81]: Inline? :DDDDDDDDD

Comment (aclevername) [reply pkg/install/installer.go:81]: fineeeeeee
